hash-format = "sha256"

[[files]]
file = "mods/additional-structures.pw.toml"
hash = "1acdeda01f4109d8f5029d05afd4d9b83d20a0ecf0b46dea93ad792e18275ddd"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "c056eed08505e17d24ad0d32e8d7d29ad6c0f0b728edf2f445bead68cf9d1189"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "8e10074e608f8cb8edfdaa4ccb5b951d8a07f9ff401cded3214c9ad87c5c936d"
metafile = true

[[files]]
file = "mods/blossomtpa.pw.toml"
hash = "6e52a1eae9cd8d5232d21914d741332900f5830afd94ae06e239dc9829541c0a"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/carpet-extra-1.21.11-1.4.177.jar"
hash = "3e45bd255dfa388fbca4992eb5e07e7cd1ccb3efff33676a5135b8e96a44cac9"

[[files]]
file = "mods/carpet-extra-extras.pw.toml"
hash = "5c1519fec90413378e6043a1e7866db2d19278d51d4f5c73ed1fcd48cad58888"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "de450bfc1e243b1e21f07b54278344e6075c198d32e57efc51cd3092b690a1f0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "eaa52d6ff1bcb539956d50626085d9185eca346fabcf6b3c176c53192b9958ec"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "a597f142f290e412e47ec4c9d5e6b03ebeff17584c0401fea0f062adfbda3ce4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "cdc66a084161b07f0f07e8a445272862270f1f7be71a8ec94959365395eadc86"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "bef0d78723bcf15335544a175244cb43416a58977e2b7551a7b5200a85af3bfa"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "c8c5df688622763ec590fda0b1c4d4adfd0152668db433f342cecd99fdd3fa0b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f12c997be9172dbf374708c4bdd1f8ef58081ccf7348dcddbf8cc8edac10b0f8"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "282673fc955317d4c82c1366f5ca5f0528ce1574071017fc8dffa81467147f55"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7f26c8df78d02b1d63a723a3a45b838415126da5296ac67b0414e564da30a421"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "67116d1cf5d38dfd27aded9d675afcc625d720a4d457660ff82db760934d9f4d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/no-portals.pw.toml"
hash = "fd4f31a4f698ca86091b0fc36914f934ca7e15493d97a2b74282303e427baa41"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "49e60e67eff7854052e260a9747a73bc818901c6be87d92060ea163b11f3b00e"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "07a55beb980b28c646f8068387b8f23434c7e583f9061af7a1e056d2e60658fd"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "c064e431015fe06786c17e18b8cfc28751a994e2ee251a357c0043a72f649403"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/squaremap.pw.toml"
hash = "8b17587d19d77d0fb343a075759c032474ebc32b941dcd0d2e48a6528736a18d"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "a66da60b40337e8bb57d81aef0f0c168771f2c6d8ae9d5e4af24031da2320795"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "70cd30931bd186fd3f9770062dd998774ac9e1c0cf478938a62d5815ffdcfe5b"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "f19a743dcab0927ec66da55e57993563fc539c3b50733104152da71c18f8abf4"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "9472dc630ee1dc9a345f49669323e1688c26662cee1fb6a2bb336e84a5dd0fd4"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "03e7ff71a73cf26ace9eda49606f2baa1d78dcac585d494478dd605e06f63ba8"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "2b521d51539ceea11c6c5310ff2dcfa38cfb8084558355b4bfbd0fde177ab912"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "9ce3767540efbf35e0a0c266040c9879efc9136ec59cd38e06e45b3c3c3e90e0"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "b227e85e0e318e43baa9dcc63af10a9b850e0055ee3c1ac52b79c7557e813637"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "398fc0aeb16146cc18016f3735ea27a47eb888650f1b31d152e19398397c6157"
metafile = true

[[files]]
file = "world/datapacks/Terraphilic-v1.2.0.zip"
hash = "6d5d34771a2726400933cf5d40e07d92635a1fedf659a3ca4ed8bc9720e513e8"
